---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: develop
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: develop
  url: https://github.com/dhifallahf1/flux-esign-prod.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: develop
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: develop
